//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_ProductBinds
    {
        public long Id { get; set; }
        public long ProdudctId { get; set; }
        public string BindSkuId { get; set; }
        public int SortNum { get; set; }
        public decimal SalePrice { get; set; }
        public int SaleNum { get; set; }
    
        public virtual Himall_SKUs Himall_SKUs { get; set; }
    }
}
