//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.OrderEnum;
    public partial class Himall_Topics
    {
        public Himall_Topics()
        {
            this.Himall_TopicModules = new HashSet<Himall_TopicModules>();
            this.Himall_MobileHomeTopics = new HashSet<Himall_MobileHomeTopics>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        private string frontCoverImage { get; set; }
        private string topImage { get; set; }
        private string backgroundImage { get; set; }
        public PlatformType PlatForm { get; set; }
        public string Tags { get; set; }
        public long ShopId { get; set; }
        public bool IsRecommend { get; set; }
        public string Descriptions { get; set; }
        private string destailBarImage { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string DomainName { get; set; }
        private string bgThumbnail { get; set; }
    
        public virtual ICollection<Himall_TopicModules> Himall_TopicModules { get; set; }
        public virtual ICollection<Himall_MobileHomeTopics> Himall_MobileHomeTopics { get; set; }
    }
}
