//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.OrderEnum;
    public partial class Himall_OrderQueue
    {
        public long OrderID { get; set; }
        public System.DateTime OrderTime { get; set; }
        public OrderQueueOperateType OrderQueueType { get; set; }
        public int FailCount { get; set; }
        public System.DateTime PushTime { get; set; }
    }
}
