//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_SKUs
    {
        public Himall_SKUs()
        {
            this.Himall_ProductBinds = new HashSet<Himall_ProductBinds>();
        }
    
        public string Id { get; set; }
        public long ProductId { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Version { get; set; }
        public string Sku { get; set; }
        public long Stock { get; set; }
        public decimal CostPrice { get; set; }
        public decimal SalePrice { get; set; }
        public string ProductBarCode { get; set; }
        public string CustomsCode { get; set; }
        public int TaxRate { get; set; }
        public decimal PushCustomsPrice { get; set; }
        public long MaxSaleStock { get; set; }
        public int GiveOtherPercent { get; set; }
        public System.DateTime LastModifyTime { get; set; }
    
        public virtual ICollection<Himall_ProductBinds> Himall_ProductBinds { get; set; }
        public virtual Himall_Products Himall_Products { get; set; }
    }
}
