//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_TopicModules
    {
        public Himall_TopicModules()
        {
            this.Himall_ModuleProducts = new HashSet<Himall_ModuleProducts>();
        }
    
        public long Id { get; set; }
        public long TopicId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Himall_ModuleProducts> Himall_ModuleProducts { get; set; }
        public virtual Himall_Topics Himall_Topics { get; set; }
    }
}
