//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Categories
    {
        public Himall_Categories()
        {
            this.Himall_BusinessCategories = new HashSet<Himall_BusinessCategories>();
            this.Himall_FloorCategories = new HashSet<Himall_FloorCategories>();
            this.Himall_HomeCategories = new HashSet<Himall_HomeCategories>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public long DisplaySequence { get; set; }
        public long ParentCategoryId { get; set; }
        public int Depth { get; set; }
        public string Path { get; set; }
        public string RewriteName { get; set; }
        public bool HasChildren { get; set; }
        public long TypeId { get; set; }
        public decimal CommisRate { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Keywords { get; set; }
        public string DomainName { get; set; }
        public int TradeType { get; set; }
        public System.DateTime LastModifyTime { get; set; }
        public string IndexIcon { get; set; }
        public string IndexDomainName { get; set; }
        public bool IsRecommend { get; set; }
    
        public virtual ICollection<Himall_BusinessCategories> Himall_BusinessCategories { get; set; }
        public virtual Himall_Types Himall_Types { get; set; }
        public virtual ICollection<Himall_FloorCategories> Himall_FloorCategories { get; set; }
        public virtual ICollection<Himall_HomeCategories> Himall_HomeCategories { get; set; }
    }
}
