//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_StaticPageConfigModules
    {
        public Himall_StaticPageConfigModules()
        {
            this.Himall_ModuleStaticPageProducts = new HashSet<Himall_ModuleStaticPageProducts>();
        }
    
        public long Id { get; set; }
        public long StaPageId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        private string pcBannerImage { get; set; }
        public Nullable<int> StyleType { get; set; }
        private string wapBannerImage { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual ICollection<Himall_ModuleStaticPageProducts> Himall_ModuleStaticPageProducts { get; set; }
        public virtual Himall_StaticPageConfig Himall_StaticPageConfig { get; set; }
    }
}
