//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Distributor
    {
        public Himall_Distributor()
        {
            this.Himall_DistributorProfit = new HashSet<Himall_DistributorProfit>();
            this.Himall_DistributorVisit = new HashSet<Himall_DistributorVisit>();
            this.Himall_DistributorSettlement = new HashSet<Himall_DistributorSettlement>();
            this.Himall_Members = new HashSet<Himall_Members>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Code { get; set; }
        public string ProvinceCode { get; set; }
        public string CityCode { get; set; }
        public string OwnerName { get; set; }
        public string IDCard { get; set; }
        public string LinkTel { get; set; }
        public Nullable<int> IsUse { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ChargeType { get; set; }
        public Nullable<decimal> ChargeRate { get; set; }
        public string IDCard_Pic { get; set; }
        public string IDCard_Pic2 { get; set; }
        public Nullable<int> LevelId { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public int CodeNumber { get; set; }
        public Nullable<System.DateTime> CodeTime { get; set; }
    
        public virtual ICollection<Himall_DistributorProfit> Himall_DistributorProfit { get; set; }
        public virtual ICollection<Himall_DistributorVisit> Himall_DistributorVisit { get; set; }
        public virtual ICollection<Himall_DistributorSettlement> Himall_DistributorSettlement { get; set; }
        public virtual ICollection<Himall_Members> Himall_Members { get; set; }
    }
}
