//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using Enum;
    using System;
    using System.Collections.Generic;

    public partial class Himall_Products
    {
        public Himall_Products()
        {
            this.Himall_BrowsingHistory = new HashSet<Himall_BrowsingHistory>();
            this.Himall_Favorites = new HashSet<Himall_Favorites>();
            this.Himall_FloorProducts = new HashSet<Himall_FloorProducts>();
            this.Himall_LimitTimeMarket = new HashSet<Himall_LimitTimeMarket>();
            this.Himall_ModuleProducts = new HashSet<Himall_ModuleProducts>();
            this.Himall_ProductAttributes = new HashSet<Himall_ProductAttributes>();
            this.Himall_ProductComments = new HashSet<Himall_ProductComments>();
            this.Himall_ProductConsultations = new HashSet<Himall_ProductConsultations>();
            this.Himall_ProductShopCategories = new HashSet<Himall_ProductShopCategories>();
            this.Himall_ProductVistis = new HashSet<Himall_ProductVistis>();
            this.Himall_ShopHomeModuleProducts = new HashSet<Himall_ShopHomeModuleProducts>();
            this.Himall_ShoppingCarts = new HashSet<Himall_ShoppingCarts>();
            this.Himall_SKUs = new HashSet<Himall_SKUs>();
            this.Himall_FloorTablDetails = new HashSet<Himall_FloorTablDetails>();
            this.Himall_MobileHomeProducts = new HashSet<Himall_MobileHomeProducts>();
            this.Himall_PromotionActivityItem = new HashSet<Himall_PromotionActivityItem>();
            this.Himall_VShopLimitTime = new HashSet<Himall_VShopLimitTime>();
        }
    
        public long Id { get; set; }
        public long ShopId { get; set; }
        public long CategoryId { get; set; }
        public string CategoryPath { get; set; }
        public long TypeId { get; set; }
        public long BrandId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ShortDescription { get; set; }
        public ProductEnum.ProductSaleStatus SaleStatus { get; set; }
        public ProductEnum.ProductAuditStatus AuditStatus { get; set; }
        public Nullable<int> EarlyWarning { get; set; }
        public System.DateTime AddedDate { get; set; }
        public long DisplaySequence { get; set; }
        private string imagePath { get; set; }
        public decimal MarketPrice { get; set; }
        public decimal MinSalePrice { get; set; }
        public bool HasSKU { get; set; }
        public long VistiCounts { get; set; }
        public long SaleCounts { get; set; }
        public long FreightTemplateId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string MeasureUnit { get; set; }
        public int TradeType { get; set; }
        public string ImageCount { get; set; }
        public string TaxNumber { get; set; }
        public string ModelName { get; set; }
        public decimal ShareMoney { get; set; }
        public string DomainName { get; set; }
        public int IsVirtualProduct { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> OnlineDate { get; set; }
        public Nullable<System.DateTime> OffDate { get; set; }
        public int RecordType { get; set; }
        public int OnlyShowInOtherPlate { get; set; }
        public int PreSale { get; set; }
        public Nullable<System.DateTime> PreStarTime { get; set; }
        public int IsSinglePackageMail { get; set; }
        public System.DateTime LastModifyTime { get; set; }
        private bool IsLTM { get; set; }
        private long LTMId { get; set; }
        private string LTMTitle { get; set; }
        private Nullable<System.DateTime> LTMStartTime { get; set; }
        private Nullable<System.DateTime> LTMEndTime { get; set; }
        private decimal LTMPrice { get; set; }
        private Nullable<System.DateTime> LTMSyncTime { get; set; }
        public Nullable<System.DateTime> FirstPublishTime { get; set; }
        public int ActivityType { get; set; }
        public decimal ActivityPrice { get; set; }
        public int ActivityID { get; set; }
        public Nullable<System.DateTime> ActivitySyncTime { get; set; }
        public int SaleQuantity { get; set; }
    
        public virtual ICollection<Himall_BrowsingHistory> Himall_BrowsingHistory { get; set; }
        public virtual ICollection<Himall_Favorites> Himall_Favorites { get; set; }
        public virtual ICollection<Himall_FloorProducts> Himall_FloorProducts { get; set; }
        public virtual ICollection<Himall_LimitTimeMarket> Himall_LimitTimeMarket { get; set; }
        public virtual ICollection<Himall_ModuleProducts> Himall_ModuleProducts { get; set; }
        public virtual ICollection<Himall_ProductAttributes> Himall_ProductAttributes { get; set; }
        public virtual ICollection<Himall_ProductComments> Himall_ProductComments { get; set; }
        public virtual ICollection<Himall_ProductConsultations> Himall_ProductConsultations { get; set; }
        public virtual Himall_ProductDescriptions Himall_ProductDescriptions { get; set; }
        public virtual ICollection<Himall_ProductShopCategories> Himall_ProductShopCategories { get; set; }
        public virtual ICollection<Himall_ProductVistis> Himall_ProductVistis { get; set; }
        public virtual ICollection<Himall_ShopHomeModuleProducts> Himall_ShopHomeModuleProducts { get; set; }
        public virtual ICollection<Himall_ShoppingCarts> Himall_ShoppingCarts { get; set; }
        public virtual ICollection<Himall_SKUs> Himall_SKUs { get; set; }
        public virtual ICollection<Himall_FloorTablDetails> Himall_FloorTablDetails { get; set; }
        public virtual Himall_FreightTemplate Himall_FreightTemplate { get; set; }
        public virtual ICollection<Himall_MobileHomeProducts> Himall_MobileHomeProducts { get; set; }
        public virtual ICollection<Himall_PromotionActivityItem> Himall_PromotionActivityItem { get; set; }
        public virtual ICollection<Himall_VShopLimitTime> Himall_VShopLimitTime { get; set; }
    }
}
