//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_HomeFloors
    {
        public Himall_HomeFloors()
        {
            this.Himall_FloorBrands = new HashSet<Himall_FloorBrands>();
            this.Himall_FloorCategories = new HashSet<Himall_FloorCategories>();
            this.Himall_FloorProducts = new HashSet<Himall_FloorProducts>();
            this.Himall_FloorTabls = new HashSet<Himall_FloorTabls>();
            this.Himall_FloorTopics = new HashSet<Himall_FloorTopics>();
        }
    
        public long Id { get; set; }
        public string FloorName { get; set; }
        public string SubName { get; set; }
        public long DisplaySequence { get; set; }
        public bool IsShow { get; set; }
        public long StyleLevel { get; set; }
        public string DefaultTabName { get; set; }
        private string floorIcon { get; set; }
        public string DomainName { get; set; }
        public int TradeType { get; set; }
        public long ShopId { get; set; }
    
        public virtual ICollection<Himall_FloorBrands> Himall_FloorBrands { get; set; }
        public virtual ICollection<Himall_FloorCategories> Himall_FloorCategories { get; set; }
        public virtual ICollection<Himall_FloorProducts> Himall_FloorProducts { get; set; }
        public virtual ICollection<Himall_FloorTabls> Himall_FloorTabls { get; set; }
        public virtual ICollection<Himall_FloorTopics> Himall_FloorTopics { get; set; }
    }
}
