//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Merchants
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Service { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
        public string Mailbox { get; set; }
        public string Telephone { get; set; }
        public string Remark { get; set; }
        public long State { get; set; }
    }
}
