//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Shops
    {
        public Himall_Shops()
        {
            this.Himall_CashDeposit = new HashSet<Himall_CashDeposit>();
            this.Himall_Coupon = new HashSet<Himall_Coupon>();
            this.Himall_CouponRecord = new HashSet<Himall_CouponRecord>();
            this.Himall_ProductComments = new HashSet<Himall_ProductComments>();
            this.Himall_ShopBrandApplys = new HashSet<Himall_ShopBrandApplys>();
            this.Himall_ShopBrands = new HashSet<Himall_ShopBrands>();
            this.Himall_StatisticOrderComments = new HashSet<Himall_StatisticOrderComments>();
            this.Himall_VShop = new HashSet<Himall_VShop>();
        }
    
        public long Id { get; set; }
        public long GradeId { get; set; }
        public string ShopName { get; set; }
        public string Logo { get; set; }
        public string SubDomains { get; set; }
        public string Theme { get; set; }
        public bool IsSelf { get; set; }
        public int ShopStatus { get; set; }
        public string RefuseReason { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CompanyName { get; set; }
        public int CompanyRegionId { get; set; }
        public string CompanyAddress { get; set; }
        public int ReturnRegionId { get; set; }
        public string ReturnAddress { get; set; }
        public string CompanyPhone { get; set; }
        public int CompanyEmployeeCount { get; set; }
        public decimal CompanyRegisteredCapital { get; set; }
        public string ContactsName { get; set; }
        public string ContactsPhone { get; set; }
        public string ContactsEmail { get; set; }
        public string BusinessLicenceNumber { get; set; }
        public string BusinessLicenceNumberPhoto { get; set; }
        public int BusinessLicenceRegionId { get; set; }
        public Nullable<System.DateTime> BusinessLicenceStart { get; set; }
        public Nullable<System.DateTime> BusinessLicenceEnd { get; set; }
        public string BusinessSphere { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationCodePhoto { get; set; }
        public string GeneralTaxpayerPhot { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public int BankRegionId { get; set; }
        public string BankPhoto { get; set; }
        public string TaxRegistrationCertificate { get; set; }
        public string TaxpayerId { get; set; }
        public string TaxRegistrationCertificatePhoto { get; set; }
        public string PayPhoto { get; set; }
        public string PayRemark { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string SenderPhone { get; set; }
        public decimal Freight { get; set; }
        public decimal FreeFreight { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> SenderRegionId { get; set; }
        public string BusinessLicenseCert { get; set; }
        public string ProductCert { get; set; }
        public string OtherCert { get; set; }
        public string legalPerson { get; set; }
        public Nullable<System.DateTime> CompanyFoundingDate { get; set; }
        public string DomainName { get; set; }
        public int BusinessLicenseCertImgNums { get; set; }
        public int ProductCertImgNums { get; set; }
        public int OtherCertImgNums { get; set; }
        public Nullable<long> ErpShopID { get; set; }
        public int IsNoTax { get; set; }
        public int TradeType { get; set; }
        public int SortNumber { get; set; }
        public System.DateTime LastModifyTime { get; set; }
    
        public virtual ICollection<Himall_CashDeposit> Himall_CashDeposit { get; set; }
        public virtual ICollection<Himall_Coupon> Himall_Coupon { get; set; }
        public virtual ICollection<Himall_CouponRecord> Himall_CouponRecord { get; set; }
        public virtual ICollection<Himall_ProductComments> Himall_ProductComments { get; set; }
        public virtual ICollection<Himall_ShopBrandApplys> Himall_ShopBrandApplys { get; set; }
        public virtual ICollection<Himall_ShopBrands> Himall_ShopBrands { get; set; }
        public virtual ICollection<Himall_StatisticOrderComments> Himall_StatisticOrderComments { get; set; }
        public virtual ICollection<Himall_VShop> Himall_VShop { get; set; }
    }
}
