//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_StaticPageConfig
    {
        public Himall_StaticPageConfig()
        {
            this.Himall_StaticPageConfigModules = new HashSet<Himall_StaticPageConfigModules>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        private string topImage { get; set; }
        public int PlatForm { get; set; }
        public string Tags { get; set; }
        public long ShopId { get; set; }
        public bool IsRecommend { get; set; }
        public string DomainName { get; set; }
        private string wapTopImage { get; set; }
    
        public virtual ICollection<Himall_StaticPageConfigModules> Himall_StaticPageConfigModules { get; set; }
    }
}
