//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.UserEnum;
    public partial class Himall_MemberTixianRecord
    {
        public long Id { get; set; }
        public long MemberAccountId { get; set; }
        public System.DateTime AddDate { get; set; }
        public TixianStatus Status { get; set; }
        public Nullable<decimal> Jine { get; set; }
        public string QuxiaoYuanyi { get; set; }
        public string RealName { get; set; }
        public int AccountType { get; set; }
        public string BankType { get; set; }
        public string BankCardNumber { get; set; }
        public string CellPhone { get; set; }
        public string AccountNumber { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string BankBranch { get; set; }
        public string Remarks { get; set; }
    
        public virtual Himall_MemberAccount Himall_MemberAccount { get; set; }
    }
}
