//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_VShopLimitTime
    {
        public long Id { get; set; }
        public Nullable<long> LimitTimeMarketId { get; set; }
        private string imagePath { get; set; }
        public int SortNum { get; set; }
        public string DomainName { get; set; }
        public Nullable<long> ProductId { get; set; }
    
        public virtual Himall_LimitTimeMarket Himall_LimitTimeMarket { get; set; }
        public virtual Himall_Products Himall_Products { get; set; }
    }
}
