//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_CouponPackage
    {
        public long Id { get; set; }
        public long ShopId { get; set; }
        public string PackageName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string PackageSN { get; set; }
        public int Status { get; set; }
        public int TogetherFail { get; set; }
    }
}
