//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using Enum;
    using System;
    using System.Collections.Generic;

    public partial class Himall_Express
    {
        public Himall_Express()
        {
            this.Himall_ExpressDetail = new HashSet<Himall_ExpressDetail>();
        }
    
        public long Id { get; set; }
        public string ShipOrderNumber { get; set; }
        public ExpressEnum.ExpressStatus Status { get; set; }
        public string ExpressCompanyName { get; set; }
        public string Message { get; set; }
        public ExpressEnum.ExpressReceiveStatus ReceiveStatus { get; set; }
        public string Condition { get; set; }
        public bool IsCheck { get; set; }
        public System.DateTime FirstSubscribeTime { get; set; }
        public System.DateTime LastSubscribeTime { get; set; }
        public int SubscribeCount { get; set; }
        public System.DateTime LastModifyTime { get; set; }
        public string RegionFullName { get; set; }
    
        public virtual ICollection<Himall_ExpressDetail> Himall_ExpressDetail { get; set; }
    }
}
