//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.OrderEnum;
    using static Enum.SystemEnum;
    public partial class Himall_Menus
    {
        public long Id { get; set; }
        public long ParentId { get; set; }
        public long ShopId { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public short Depth { get; set; }
        public short Sequence { get; set; }
        public string FullIdPath { get; set; }
        public PlatformType Platform { get; set; }
        public Nullable<UrlTypes> UrlType { get; set; }
    }
}
