//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.SystemEnum;
    public partial class Himall_SlideAds
    {
        public long Id { get; set; }
        public long ShopId { get; set; }
        private string imageUrl { get; set; }
        public string Url { get; set; }
        public long DisplaySequence { get; set; }
        public SlideAdType TypeId { get; set; }
        public string Description { get; set; }
        public string DomainName { get; set; }
        public string BackColor { get; set; }
        public string AppUrl { get; set; }
    }
}
