//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_MemberIncom
    {
        public long Id { get; set; }
        public long UserID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> SubUserID { get; set; }
        public long Count { get; set; }
        public decimal TotalCommission { get; set; }
        public decimal Commission { get; set; }
        public int IsUse { get; set; }
        public string Remark { get; set; }
        public long ProductId { get; set; }
        public string SKUId { get; set; }
        public long ReferId { get; set; }
        public int CommissionRate { get; set; }
    
        public virtual Himall_Members Himall_Members { get; set; }
    }
}
