//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_ModuleProducts
    {
        public long Id { get; set; }
        public long ModuleId { get; set; }
        public long ProductId { get; set; }
        public long DisplaySequence { get; set; }
    
        public virtual Himall_Products Himall_Products { get; set; }
        public virtual Himall_TopicModules Himall_TopicModules { get; set; }
    }
}
