//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_CashDepositDetail
    {
        public long Id { get; set; }
        public long CashDepositId { get; set; }
        public System.DateTime AddDate { get; set; }
        public decimal Balance { get; set; }
        public string Operator { get; set; }
        public string Description { get; set; }
        public Nullable<int> RechargeWay { get; set; }
    
        public virtual Himall_CashDeposit Himall_CashDeposit { get; set; }
    }
}
