//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.OrderEnum;
    public partial class Himall_OrderRefunds
    {
        public Himall_OrderRefunds()
        {
            this.Himall_OrderRefundOperationLogs = new HashSet<Himall_OrderRefundOperationLogs>();
        }
    
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long OrderItemId { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public long UserId { get; set; }
        public string Applicant { get; set; }
        public string ContactPerson { get; set; }
        public string ContactCellPhone { get; set; }
        public string RefundAccount { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public decimal Amount { get; set; }
        public string Reason { get; set; }
        public OrderRefundAuditStatus SellerAuditStatus { get; set; }
        public System.DateTime SellerAuditDate { get; set; }
        public string SellerRemark { get; set; }
        public OrderRefundConfirmStatus ManagerConfirmStatus { get; set; }
        public System.DateTime ManagerConfirmDate { get; set; }
        public string ManagerRemark { get; set; }
        public bool IsReturn { get; set; }
        public string ExpressCompanyName { get; set; }
        public string ShipOrderNumber { get; set; }
        public string Payee { get; set; }
        public string PayeeAccount { get; set; }
        public OrderRefundMode RefundMode { get; set; }
        public Nullable<System.DateTime> BuyerDeliverDate { get; set; }
        public Nullable<System.DateTime> SellerConfirmArrivalDate { get; set; }
        public int GoodsReturnIsBreak { get; set; }
        public string GoodsReturnRemark { get; set; }
        public string GoodsReturnExpName { get; set; }
        public string GoodsReturnShipOrderNo { get; set; }
        public Nullable<System.DateTime> GoodsReturnExpDate { get; set; }
        public Nullable<System.DateTime> BuyerTakeGoodsDate { get; set; }
        public int GoodsReturnCount { get; set; }
        public Nullable<decimal> DealAmount { get; set; }
        public Nullable<int> TradeType { get; set; }
        public int IsAgainRefund { get; set; }
        public string RefundMoneyReMark { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> OffPrice { get; set; }
        public string OffPriceMark { get; set; }
        public string OffPriceType { get; set; }
    
        public virtual Himall_OrderItems Himall_OrderItems { get; set; }
        public virtual ICollection<Himall_OrderRefundOperationLogs> Himall_OrderRefundOperationLogs { get; set; }
    }
}
