//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_MemberAccount
    {
        public Himall_MemberAccount()
        {
            this.Himall_MemberBankInfo = new HashSet<Himall_MemberBankInfo>();
            this.Himall_MemberTixianRecord = new HashSet<Himall_MemberTixianRecord>();
        }
    
        public long Id { get; set; }
        public decimal BalancePrice { get; set; }
        public decimal FreezPrice { get; set; }
        public long MemberId { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Himall_Members Himall_Members { get; set; }
        public virtual ICollection<Himall_MemberBankInfo> Himall_MemberBankInfo { get; set; }
        public virtual ICollection<Himall_MemberTixianRecord> Himall_MemberTixianRecord { get; set; }
    }
}
