//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_HomeCategoryTextLinkRows
    {
        public long Id { get; set; }
        public int RowId { get; set; }
        public string TextLink { get; set; }
        public string UrlLink { get; set; }
        public short DisplaySequence { get; set; }
        public sbyte IsShow { get; set; }
        public int TradeType { get; set; }
    }
}
