//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_ShopBrandApplys
    {
        public int Id { get; set; }
        public long ShopId { get; set; }
        public Nullable<long> BrandId { get; set; }
        public string BrandName { get; set; }
        public string Logo { get; set; }
        public string Description { get; set; }
        public string AuthCertificate { get; set; }
        public int ApplyMode { get; set; }
        public string Remark { get; set; }
        public int AuditStatus { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public string DomainName { get; set; }
    
        public virtual Himall_Brands Himall_Brands { get; set; }
        public virtual Himall_Shops Himall_Shops { get; set; }
    }
}
