//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Tax
    {
        public string TaxNumber { get; set; }
        public string ModelName { get; set; }
        public string Unit { get; set; }
        public string TaxPrice { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public string Remark { get; set; }
    }
}
