//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_OrderOperationLogs
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string Operator { get; set; }
        public System.DateTime OperateDate { get; set; }
        public string OperateContent { get; set; }
    
        public virtual Himall_Orders Himall_Orders { get; set; }
    }
}
