//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_ProductConsultations
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string ConsultationContent { get; set; }
        public System.DateTime ConsultationDate { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    
        public virtual Himall_Products Himall_Products { get; set; }
    }
}
