//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Accounts
    {
        public Himall_Accounts()
        {
            this.Himall_AccountPurchaseAgreement = new HashSet<Himall_AccountPurchaseAgreement>();
            this.Himall_AccountDetails = new HashSet<Himall_AccountDetails>();
        }
    
        public long Id { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public System.DateTime AccountDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Status { get; set; }
        public decimal ProductActualPaidAmount { get; set; }
        public decimal FreightAmount { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal RefundCommissionAmount { get; set; }
        public decimal RefundAmount { get; set; }
        public decimal AdvancePaymentAmount { get; set; }
        public decimal PeriodSettlement { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Himall_AccountPurchaseAgreement> Himall_AccountPurchaseAgreement { get; set; }
        public virtual ICollection<Himall_AccountDetails> Himall_AccountDetails { get; set; }
    }
}
