//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_AccountPurchaseAgreement
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public long ShopId { get; set; }
        public System.DateTime Date { get; set; }
        public long PurchaseAgreementId { get; set; }
        public decimal AdvancePayment { get; set; }
        public System.DateTime FinishDate { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    
        public virtual Himall_Accounts Himall_Accounts { get; set; }
    }
}
