//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.ProductEnum;
    public partial class Himall_LimitTimeMarket
    {
        public Himall_LimitTimeMarket()
        {
            this.Himall_VShopLimitTime = new HashSet<Himall_VShopLimitTime>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public long ProductId { get; set; }
        public string ProductName { get; set; }
        public string CategoryName { get; set; }
        public LimitTimeMarketAuditStatus AuditStatus { get; set; }
        public System.DateTime AuditTime { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public decimal Price { get; set; }
        public decimal RecentMonthPrice { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Stock { get; set; }
        public int SaleCount { get; set; }
        public string CancelReson { get; set; }
        public int MaxSaleCount { get; set; }
        public string ProductAd { get; set; }
        public decimal MinPrice { get; set; }
        public string ImagePath { get; set; }
        public decimal MarketPrice { get; set; }
        public string CountryName { get; set; }
        public string CountryLogo { get; set; }
        public System.DateTime LastModifyTime { get; set; }
    
        public virtual Himall_Products Himall_Products { get; set; }
        public virtual ICollection<Himall_VShopLimitTime> Himall_VShopLimitTime { get; set; }
    }
}
