//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_ActivityPayRecord
    {
        public long Id { get; set; }
        public string VerifyCode { get; set; }
        public long UserId { get; set; }
        public int Status { get; set; }
        public string OrderId { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public long DistributorId { get; set; }
        public string TradNo { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string PaymentTypeName { get; set; }
        public string PaymentTypeGateway { get; set; }
        public int ActivityType { get; set; }
    }
}
