//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.SystemEnum;
    public partial class Himall_CouponRecord
    {
        public long Id { get; set; }
        public long CouponId { get; set; }
        public string CounponSN { get; set; }
        public System.DateTime CounponTime { get; set; }
        public string UserName { get; set; }
        public long UserId { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public Nullable<long> OrderId { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public CounponStatuses CounponStatus { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ChildIdSN { get; set; }
        public long CouponPackageId { get; set; }
    
        public virtual Himall_Coupon Himall_Coupon { get; set; }
        public virtual Himall_Shops Himall_Shops { get; set; }
    }
}
