//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Pmail
    {
        public Himall_Pmail()
        {
            this.Himall_PmailCecord = new HashSet<Himall_PmailCecord>();
        }
    
        public long PId { get; set; }
        public Nullable<int> PCategory { get; set; }
        public Nullable<int> PSender { get; set; }
        public string PTitle { get; set; }
        public string PContent { get; set; }
        public string PTime { get; set; }
        public string PState { get; set; }
        public int MessageStatus { get; set; }
    
        public virtual ICollection<Himall_PmailCecord> Himall_PmailCecord { get; set; }
    }
}
