//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.SystemEnum;
    public partial class Himall_Opinions
    {
        public long Id { get; set; }
        public string Describe { get; set; }
        public string Email { get; set; }
        public string Improve { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<OpinionSource> SourceType { get; set; }
        public Nullable<OpinionStatus> Status { get; set; }
    }
}
