//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    using static Enum.OrderEnum;
    public partial class Himall_FreightTemplate
    {
        public Himall_FreightTemplate()
        {
            this.Himall_FreightAreaContent = new HashSet<Himall_FreightAreaContent>();
            this.Himall_Products = new HashSet<Himall_Products>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SourceAddress { get; set; }
        public string SendTime { get; set; }
        public FreightTemplateType IsFree { get; set; }
        public ValuationMethodType ValuationMethod { get; set; }
        public Nullable<int> ShippingMethod { get; set; }
        public long ShopID { get; set; }
        public long BondedId { get; set; }
    
        public virtual ICollection<Himall_FreightAreaContent> Himall_FreightAreaContent { get; set; }
        public virtual ICollection<Himall_Products> Himall_Products { get; set; }
    }
}
