//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_Brands
    {
        public Himall_Brands()
        {
            this.Himall_FloorBrands = new HashSet<Himall_FloorBrands>();
            this.Himall_ShopBrandApplys = new HashSet<Himall_ShopBrandApplys>();
            this.Himall_ShopBrands = new HashSet<Himall_ShopBrands>();
            this.Himall_TypeBrands = new HashSet<Himall_TypeBrands>();
            this.Himall_FocusBrand = new HashSet<Himall_FocusBrand>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long DisplaySequence { get; set; }
        private string logo { get; set; }
        public string RewriteName { get; set; }
        public string Description { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Keywords { get; set; }
        public bool IsRecommend { get; set; }
        public string AuditMsg { get; set; }
        public string DomainName { get; set; }
        public long CountryMarkId { get; set; }
        public System.DateTime LastModifyTime { get; set; }
        private string descriptionPic { get; set; }
    
        public virtual Himall_CountryMark Himall_CountryMark { get; set; }
        public virtual ICollection<Himall_FloorBrands> Himall_FloorBrands { get; set; }
        public virtual ICollection<Himall_ShopBrandApplys> Himall_ShopBrandApplys { get; set; }
        public virtual ICollection<Himall_ShopBrands> Himall_ShopBrands { get; set; }
        public virtual ICollection<Himall_TypeBrands> Himall_TypeBrands { get; set; }
        public virtual ICollection<Himall_FocusBrand> Himall_FocusBrand { get; set; }
    }
}
