//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using Enum;
    using System;
    using System.Collections.Generic;

    public partial class Himall_FloorTopics
    {
        public long Id { get; set; }
        public long FloorId { get; set; }
        public SystemEnum.Position TopicType { get; set; }
        private string topicImage { get; set; }
        public string TopicName { get; set; }
        public string Url { get; set; }
        public string DomainName { get; set; }
        public string AppUrl { get; set; }
    
        public virtual Himall_HomeFloors Himall_HomeFloors { get; set; }
    }
}
