//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YB.CMS.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himall_CountryMark
    {
        public Himall_CountryMark()
        {
            this.Himall_Brands = new HashSet<Himall_Brands>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> DisplaySequence { get; set; }
        private string logo { get; set; }
        public string Description { get; set; }
        public string DomainName { get; set; }
        public System.DateTime LastModifyTime { get; set; }
        public string SimpleName { get; set; }
    
        public virtual ICollection<Himall_Brands> Himall_Brands { get; set; }
    }
}
